import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { chatWithOllama } from "@/lib/ollama";
import { searchKittyManual } from "@/lib/manual-search";
import { tirePressureGuidance } from "@/lib/weather-guidance";
import { matchSoundSymptom } from "@/lib/symptom-guidance";
import { matchOwnerGuide } from "@/lib/owner-guidance";

type ChatMessage={role:"user"|"assistant";content:string};
const citationPattern=/\[Toyota Owner's Manual, p\. (\d+)\]/g;
function normalized(text:string){return text.toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function reliableAnswer(question:string,result:{answer:string;evidenceLevels:string[]},manualPages:number[]){
  const answer=normalized(result.answer),prompt=normalized(question);if(!answer||answer===prompt||answer.split(" ").length<=prompt.split(" ").length+2)return false;
  const citedPages=Array.from(result.answer.matchAll(citationPattern),match=>Number(match[1]));
  return !result.evidenceLevels.includes("Toyota manual")||(citedPages.length>0&&citedPages.every(page=>manualPages.includes(page)));
}

export async function POST(request:Request){
  const body=await request.json();const messages:Array<ChatMessage>=Array.isArray(body.messages)?body.messages:[];
  if(!messages.length||messages.length>12||messages.some(message=>!(message.role==="user"||message.role==="assistant")||typeof message.content!=="string"||message.content.length<1||message.content.length>1500))return NextResponse.json({error:"Send a short question about Kitty."},{status:400});
  const kitty=await prisma.vehicle.findFirst({where:{nickname:{equals:"Kitty"}},include:{maintenance:true,services:{orderBy:{serviceDate:"desc"},take:8},concerns:{where:{status:{not:"Resolved"}},orderBy:{dateFirstNoticed:"desc"}}}});
  if(!kitty)return NextResponse.json({error:"Kitty’s vehicle record was not found."},{status:404});
  const latestQuestion=messages[messages.length-1].content;const manualExcerpts=await searchKittyManual(latestQuestion,4);
  const context={vehicle:{nickname:kitty.nickname,year:kitty.year,make:kitty.make,model:kitty.model,trim:kitty.trim,color:kitty.color,fuelType:kitty.fuelType,transmission:kitty.transmission,currentMileage:kitty.currentMileage,purchaseMileage:kitty.purchaseMileage},savedMaintenance:kitty.maintenance.map(item=>({title:item.title,description:item.description,nextDueMileage:item.nextDueMileage,nextDueDate:item.nextDueDate,intervalMiles:item.intervalMiles,intervalMonths:item.intervalMonths,notes:item.notes})),recentService:kitty.services.map(item=>({title:item.title,category:item.category,serviceDate:item.serviceDate,mileage:item.mileage,description:item.description})),openOwnerObservations:kitty.concerns.map(item=>({title:item.title,severity:item.severity,symptoms:item.symptoms,status:item.status,mechanicNotes:item.mechanicNotes}))};
  const normalizedQuestion=normalized(latestQuestion);const asksAboutPressure=/(^| )psi( |$)/.test(normalizedQuestion)||normalizedQuestion.includes("tire pressure")||normalizedQuestion.includes("tyre pressure")||normalizedQuestion.includes("inflation pressure");if(asksAboutPressure){
    const pressurePage=await prisma.manualPage.findFirst({where:{document:{manualCode:"OM02684U"},pageNumber:323},select:{pageNumber:true,document:{select:{sourceUrl:true}}}});const citation=pressurePage?" Toyota says to measure pressure when the tires are cold—after Kitty has been parked for at least three hours or driven less than one mile—and recommends checking every two weeks or at least monthly [Toyota Owner's Manual, p. 323].":"";return NextResponse.json({answer:`Yes. ${tirePressureGuidance.cold} ${tirePressureGuidance.placard}${citation} If one tire is much lower than the others, has visible damage, or keeps losing air after adjustment, have it inspected rather than repeatedly topping it off. You can also open Conditions → Weather that matters to Kitty for today’s temperature swing and live weather guidance.`,answerKind:"verified",actions:[{label:"Open Conditions",href:"/conditions"}],evidenceLevels:pressurePage?["General explanation","Toyota manual"]:["General explanation"],sources:pressurePage?[{pageNumber:pressurePage.pageNumber,sourceUrl:`${pressurePage.document.sourceUrl}#page=${pressurePage.pageNumber}`}]:[]});
  }
  const ownerGuide=matchOwnerGuide(latestQuestion);if(ownerGuide){const {id,guide}=ownerGuide;return NextResponse.json({answer:`${guide.title}: ${guide.alert} ${guide.steps.join(" ")} Open Quick Help for the complete guide and official Toyota resource.`,answerKind:"verified",actions:[{label:id==="jump"?"Open jump-start guide":"Open Quick Help",href:`/dashboard?help=${id}`}],evidenceLevels:["General explanation"],sources:[]});}
  const soundSymptom=matchSoundSymptom(latestQuestion);if(soundSymptom){return NextResponse.json({answer:`Carfolio cannot diagnose a sound from a description alone. ${soundSymptom.copy} Stop driving safely and arrange roadside or professional help if the sound comes with changed braking or steering, strong vibration, a warning light, leaking fluid, loss of power, or difficulty controlling Kitty. Otherwise, avoid unnecessary driving and arrange an inspection. To help a mechanic, ${soundSymptom.capture.charAt(0).toLowerCase()+soundSymptom.capture.slice(1)} The Symptom Navigator can save those details as an unconfirmed owner observation.`,answerKind:"verified",actions:[{label:"Open Symptom Navigator",href:"/owner-tools?tool=symptoms"}],evidenceLevels:["General explanation"],sources:[]});}
  if((normalizedQuestion.includes("road trip")||normalizedQuestion.includes("pre trip"))&&(normalizedQuestion.includes("check")||normalizedQuestion.includes("ready")||normalizedQuestion.includes("prepare"))){
    const upcoming=kitty.maintenance.filter(item=>item.nextDueMileage&&item.nextDueMileage>=kitty.currentMileage).sort((a,b)=>(a.nextDueMileage??Infinity)-(b.nextDueMileage??Infinity)).slice(0,3);const closest=upcoming[0];const maintenanceNote=closest?.nextDueMileage?` Kitty is currently at ${kitty.currentMileage.toLocaleString()} miles. ${upcoming.filter(item=>item.nextDueMileage===closest.nextDueMileage).map(item=>item.title).join(" and ")} ${upcoming.filter(item=>item.nextDueMileage===closest.nextDueMileage).length===1?"is":"are"} next due at ${closest.nextDueMileage.toLocaleString()} miles, ${Math.max(0,closest.nextDueMileage-kitty.currentMileage).toLocaleString()} miles away.`:` Kitty is currently at ${kitty.currentMileage.toLocaleString()} miles; no upcoming mileage-based service is saved.`;const concernNote=kitty.concerns.length?` Review ${kitty.concerns.length===1?"the open owner observation":"all open owner observations"} before leaving, especially anything involving braking, steering, tires, warning lights, leaks, heat, smoke, or unusual smells.`:" No open owner observations are saved.";return NextResponse.json({answer:`Before a road trip, first enter the complete round-trip distance in Owner Tools → Planning a trip so Carfolio can compare the ending mileage with every saved service limit.${maintenanceNote}${concernNote}\n\nThen physically check: cold tire pressure using the driver-door placard, tread and visible tire damage; engine oil, coolant and washer fluid; leaks; exterior lights; wipers; registration, insurance and roadside-assistance details; and a phone charger, water, flashlight and first-aid kit. If Kitty has a warning light or a new braking, steering, overheating, smoke, fuel-odor or control problem, address it before the trip rather than relying on this checklist.`,answerKind:"verified",actions:[{label:"Open trip planner",href:"/owner-tools?tool=trip"}],evidenceLevels:["Kitty's records","General explanation"],sources:[]});
  }
  if(normalizedQuestion.includes("brake")&&normalizedQuestion.includes("pad")){
    const inspection=kitty.maintenance.find(item=>normalized(item.title).includes("brake inspection"));const page140=manualExcerpts.find(item=>item.pageNumber===140);const page390=manualExcerpts.find(item=>item.pageNumber===390);const recordNote=inspection?.nextDueMileage?` Kitty’s next saved brake inspection is due at ${inspection.nextDueMileage.toLocaleString()} miles${inspection.nextDueMileage>kitty.currentMileage?`, about ${(inspection.nextDueMileage-kitty.currentMileage).toLocaleString()} miles from now`:" and is currently due"}; this is an inspection reminder, not an automatic replacement date.`:"";const manualNote=page140?" Toyota says squealing or scraping from the brake-pad wear indicators means the pads should be checked and replaced as soon as needed [Toyota Owner's Manual, p. 140].":"";const limitNote=page390?" The manual lists minimum pad thicknesses of 1.5 mm in front and 2.0 mm in the rear [Toyota Owner's Manual, p. 390].":"";const evidenceLevels:Array<"Kitty's records"|"Toyota manual"|"General explanation">=["General explanation"];if(recordNote)evidenceLevels.unshift("Kitty's records");if(manualNote||limitNote)evidenceLevels.push("Toyota manual");return NextResponse.json({answer:`Brake pads do not have one fixed replacement interval—their life changes with traffic, hills, driving style, and pad condition. Have them inspected during routine service and replace them based on measured wear, noise, or braking symptoms.${recordNote}${manualNote}${limitNote}`,answerKind:"verified",actions:[{label:"Review maintenance",href:"/maintenance"}],evidenceLevels,sources:[page140,page390].filter(Boolean).map(item=>({pageNumber:item!.pageNumber,sourceUrl:item!.sourceUrl}))});
  }
  try{const aiMessages=[{role:"system" as const,content:`/no_think\nAnswer the user's question directly; never repeat or merely rephrase it. You are Carfolio's local educational assistant for one vehicle named Kitty. Use three evidence levels and label the relevant paragraph: "Kitty's records:" for saved mileage, maintenance, service, or observations; "Toyota manual:" for facts supported by the supplied manual excerpts; and "General explanation:" for general automotive education. You may use more than one label when needed. Return every evidence level you actually used in evidenceLevels. Every statement based on a manual excerpt must cite it as [Toyota Owner's Manual, p. PAGE]. Do not cite a page that was not supplied. If a source gives a wear condition but no fixed interval, clearly say there is no fixed interval rather than inventing one. Explicitly say when the provided excerpts do not verify an exact Toyota fact. Owner observations are not confirmed defects. Do not diagnose mechanical problems or claim the vehicle is safe to drive. Do not invent Toyota specifications, capacities, intervals, warning meanings, or procedures. For tire pressure, direct the owner to the driver-door placard. For red warnings, smoke, fuel odor, braking/steering changes, overheating, or loss of control, lead with stopping safely and contacting emergency, roadside, or professional help. Keep answers concise, first-owner friendly, and practical. Never reveal or request VIN, plate, policy, registration, address, or account data.\n\nSAVED KITTY RECORD:\n${JSON.stringify(context)}\n\nRETRIEVED TOYOTA MANUAL EXCERPTS:\n${manualExcerpts.length?JSON.stringify(manualExcerpts.map(item=>({page:item.pageNumber,text:item.text}))):"No relevant excerpt was retrieved for this question."}`},...messages.slice(-10)];let result=await chatWithOllama(aiMessages);const pages=manualExcerpts.map(item=>item.pageNumber);if(!reliableAnswer(latestQuestion,result,pages)){result=await chatWithOllama([...aiMessages,{role:"assistant",content:result.answer},{role:"user",content:`Your previous response did not answer my original question reliably. Answer this exact question now: ${latestQuestion}`}]);}if(!reliableAnswer(latestQuestion,result,pages))return NextResponse.json({error:"Carfolio could not create a reliable answer. Please reword the question and try again."},{status:502});return NextResponse.json({...result,sources:manualExcerpts.map(item=>({pageNumber:item.pageNumber,sourceUrl:item.sourceUrl}))})}catch{return NextResponse.json({error:"Carfolio could not reach local AI. Keep Ollama open and try again."},{status:502})}
}
