export type OwnerGuide={title:string;alert:string;steps:string[];resource:string;resourceLabel:string};

export const toyotaEmergencyGuides:Record<string,OwnerGuide>={
  jump:{title:"Jump Kitty’s 12-volt system",alert:"Never touch orange high-voltage parts or attempt to jump the hybrid traction battery.",steps:["Park the support vehicle close without touching Kitty. Set both parking brakes, select P, and switch lights and accessories off.","Open Kitty’s manual to the emergency-start section and expose the designated positive jump terminal in the under-hood fuse box.","Connect positive to Kitty’s jump terminal, positive to the support battery, negative to the support battery, then the final negative clamp to Kitty’s specified solid unpainted metal ground—not the fuse box or moving parts.","Start the support vehicle and let it run briefly. With the electronic key inside Kitty, press the brake firmly and press POWER once; confirm the green READY indicator.","Remove cables in reverse order. If READY does not appear, stop repeated attempts and call Toyota Roadside Assistance or a qualified service provider."],resource:"https://assets.sia.toyota.com/publications/en/om-s/OM24E1QRG/pdf/OM24E1QRG.pdf",resourceLabel:"Toyota Corolla quick reference"},
  tire:{title:"Handle Kitty’s flat tire",alert:"Do not change a wheel beside moving traffic, on a slope, or on soft or unstable ground.",steps:["Switch on hazards and stop on firm, level ground away from traffic.","Check Kitty’s trunk and owner’s manual to identify the supplied spare or puncture repair kit.","Use only the manual’s reinforced jacking points and never get under a vehicle supported only by a jack.","Follow the temporary-spare limits and arrange professional tire repair promptly."],resource:"https://www.toyota.com/owners/warranty-owners-manuals/",resourceLabel:"Find Kitty’s Toyota owner’s manual"},
  inflate:{title:"Set Kitty’s tire pressure",alert:"Use the cold PSI printed on Kitty’s driver-door placard, never the maximum pressure molded on the tire.",steps:["Check before driving or after Kitty has been parked for at least three hours.","Read the front and rear cold PSI on the driver-door placard.","Measure each tire, add air in short bursts, recheck, and replace every valve cap.","Arrange inspection for repeated pressure loss, a bulge, exposed cord, or visible damage."],resource:"https://www.toyota.com/car-tips/check-tire-pressure/",resourceLabel:"Toyota: How to check tire pressure"},
  washer:{title:"Refill Kitty’s washer fluid",alert:"Use only the reservoir marked with the windshield-spray symbol.",steps:["Park, select P, turn Kitty fully off, and let the under-hood area cool.","Identify the washer-fluid cap by its windshield/spray symbol.","Add suitable premixed washer fluid slowly and secure the cap.","Never add washer fluid to a coolant or brake-fluid reservoir."],resource:"https://www.toyota.com/car-tips/change-windshield-washer-fluid/",resourceLabel:"Toyota: Refill washer fluid"},
  oil:{title:"Plan Kitty’s oil and filter change",alert:"Hot oil, lifting, torque, and disposal make this a professional-level task without the correct equipment and manual.",steps:["Confirm the exact oil, capacity, filter, lifting points, and torque values in Kitty’s manual.","Never work under a vehicle supported only by a jack.","Verify the final level on level ground and inspect for leaks.","Use a qualified professional when uncertain and recycle used oil legally."],resource:"https://www.toyota.com/owners/express-maintenance/",resourceLabel:"Toyota Express Maintenance video"},
};

export function matchOwnerGuide(question:string){const text=question.toLowerCase().replace(/[^a-z0-9]+/g," ");if(/jump( start)?|dead (12 volt )?battery/.test(text))return {id:"jump",guide:toyotaEmergencyGuides.jump};if(/flat tire|change (a )?tire/.test(text))return {id:"tire",guide:toyotaEmergencyGuides.tire};if(/washer fluid|windshield fluid/.test(text))return {id:"washer",guide:toyotaEmergencyGuides.washer};if(/oil change|change (my |the )?oil/.test(text))return {id:"oil",guide:toyotaEmergencyGuides.oil};return null}
